networks:
  jupyter:
    driver: bridge
    name: jupyter

services:

  hub:
    build:
      context: ./hub
      dockerfile: Dockerfile
    command: jupyterhub -f /srv/jupyterhub/jupyterhub_config.py
    container_name: hub
    environment:
      JUPYTERHUB_CRYPT_KEY: "mycryptkey"
    image: hub:latest
    networks:
      - jupyter
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./hub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - ./templates:/srv/jupyterhub/templates

  icosbase:
    build:
      context: ./icosbase
      dockerfile: Dockerfile
    container_name: icosbase
    deploy:
      replicas: 0
    image: icosbase:latest
    networks:
      - jupyter

  pylib-examples:
    build:
      context: nb-content/pylib-examples
      dockerfile: ../Dockerfile
    deploy:
      replicas: 0
    image: pylib-examples:latest
    networks:
      - jupyter
    restart: on-failure

  icos-notebooks:
    build:
      context: nb-content/icos-notebooks
      dockerfile: ../Dockerfile
    deploy:
      replicas: 0
    image: icos-notebooks:latest
    networks:
      - jupyter
    restart: on-failure