site_name: ICOS Carbon Portal Jupyter Solutions
nav:
    - About: index.md
    - Jupyter Solutions: jupyter_solutions.md
    - ICOS Notebooks: icos_notebooks.md
    - How to: how_to.md
    - FAQ: faq.md

#markdown extensions:
    #- attr_list

theme:
    name: readthedocs
#   collapse_navigation: False