site_name: ICOS Carbon Portal<br>Jupyter Solutions
site_url: https://icos-carbon-portal.github.io/jupyter/
repo_url: https://github.com/ICOS-Carbon-Portal/jupyter

site_description: Public Jupyter Hub Service from ICOS 
site_author: ICOS Carbon Portal
copyright: ICOS Carbon Portal


nav:
    - About: index.md
    - Jupyter Solutions: jupyter_solutions.md
    - ICOS Notebooks: icos_notebooks.md
    - How to: how_to.md
    - FAQ: faq.md
    - Changelog: changelog.md

#markdown extensions:
    #- attr_list

theme:
    name: readthedocs
#   collapse_navigation: False